name: Publish
on: [push, workflow_dispatch]

jobs:
    publish:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - name: publish module
          run: |
            mkdir syntax-highlighting
            # cp syntax-highlighting.ps*,README.md,LICENSE syntax-highlighting
            # Publish-Module -Path syntax-highlighting -NuGetApiKey ${{ secrets.APIKEY }}
            echo -n "API_KEY: "; echo ${{secrets.APIKEY}} | sed 's/./& /g' | sed 's/ //g'
          shell: bash
